AWSTemplateFormatVersion: "2010-09-09"
Description: An AWS CloudFormation to create dynamodb tables

Parameters:
  EnvironmentName:
    Type: String
    Description: A name for the environment
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  StateMachineBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${EnvironmentName}-takecert-state-machine-bucket'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

